<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class 210622-acap-CASLETTERTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('CAS_LETTER')->delete();
        
        \DB::table('CAS_LETTER')->insert(array (
            0 => 
            array (
                'CAS_LETTER_DESC' => 'CONSULTANT_NAME
CONSULTANT_FIMM_NO
CASE_CLASSIFICATION
CASE_REMARK
CASE_REASON
CASE_START_DATE
CASE_END_DATE',
                'CAS_LETTER_ID' => 5,
                'CAS_LETTER_TITTLE' => 'TEMPLATE 1',
                'CREATE_BY' => NULL,
            ),
            1 => 
            array (
            'CAS_LETTER_DESC' => '<P CLASS="QL-ALIGN-RIGHT"><STRONG>&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;LAMPIRAN D-4</STRONG></P><P CLASS="QL-ALIGN-JUSTIFY"><STRONG>&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;</STRONG></P><P CLASS="QL-ALIGN-JUSTIFY">&NBSP;</P><P CLASS="QL-ALIGN-CENTER"><STRONG>SURAT AKUAN PETENDER</STRONG></P><P CLASS="QL-ALIGN-CENTER"><STRONG>&NBSP;</STRONG></P><P CLASS="QL-ALIGN-JUSTIFY"><STRONG>NO. TENDER : LKPU (S) 2/2020</STRONG></P><P CLASS="QL-ALIGN-JUSTIFY">&NBSP;</P><P CLASS="QL-ALIGN-JUSTIFY">KEPADA:</P><P CLASS="QL-ALIGN-JUSTIFY">&NBSP;</P><P CLASS="QL-ALIGN-JUSTIFY">LEMBAGA KELAYAKAN PROFESION UNDANG-UNDANG MALAYSIA</P><P CLASS="QL-ALIGN-JUSTIFY">UNIT 22-01, ARAS 2, MENARA 2</P><P CLASS="QL-ALIGN-JUSTIFY">MENARA KEMBAR BANK RAKYAT, </P><P CLASS="QL-ALIGN-JUSTIFY">NO. 33, JALAN RAKYAT, </P><P CLASS="QL-ALIGN-JUSTIFY">50470 KUALA LUMPUR, </P><P CLASS="QL-ALIGN-JUSTIFY">WILAYAH PERSEKUTUAN KUALA LUMPUR </P><P CLASS="QL-ALIGN-JUSTIFY">&NBSP;</P><P CLASS="QL-ALIGN-JUSTIFY">TUAN,</P><P CLASS="QL-ALIGN-JUSTIFY">&NBSP;</P><P CLASS="QL-ALIGN-JUSTIFY"><STRONG>MELAKSANAKAN KAJIAN KEPERLUAN PENGGUNA, ANALISIS DAN REKA BENTUK, PEMBANGUNAN, PENGUJIAN, LATIHAN, DAN PENYENGGARAAN PERISIAN DAN APLIKASI&NBSP;UNTUK SISTEM PENGURUSAN PEPERIKSAAN LEMBAGA KELAYAKAN PROFESION UNDANG-UNDANG, MALAYSIA (E-LPQB).</STRONG></P><P><BR></P><P CLASS="QL-ALIGN-JUSTIFY">SAYA/KAMI YANG MENURUNKAN TANDATANGAN DI BAWAH DENGAN INI MENGAMBIL BAHAGIAN UNTUK <STRONG STYLE="BACKGROUND-COLOR: YELLOW; COLOR: RGB(0, 0, 204);">&NBSP;</STRONG><STRONG>MELAKSANAKAN KAJIAN KEPERLUAN PENGGUNA, ANALISIS DAN REKA BENTUK, PEMBANGUNAN, PENGUJIAN, LATIHAN, DAN PENYENGGARAAN PERISIAN DAN APLIKASI&NBSP;UNTUK SISTEM PENGURUSAN PEPERIKSAAN LEMBAGA KELAYAKAN PROFESION UNDANG-UNDANG, MALAYSIA (E-LPQB) </STRONG>SEPERTI YANG DINYATAKAN DI DALAM LAMPIRAN D-3 – JADUAL HARGA DAN BERSETUJU UNTUK MENERIMA SERTA MEMATUHI DAN TERIKAT DENGAN SEMUA ARAHAN DAN SYARAT-SYARAT KEPADA PENYEBUT HARGA, KONTRAK DAN SPESIFIKASI YANG TERKANDUNG DALAM DOKUMEN TENDER YANG DIKEMBARKAN BERSAMA DENGAN TAWARAN INI.</P><P CLASS="QL-ALIGN-JUSTIFY">&NBSP;</P><P CLASS="QL-ALIGN-JUSTIFY">2.&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;ADALAH SAYA/KAMI DENGAN INI MENAWARKAN APLIKASI TERSEBUT BAGI JUMLAH KESELURUHAN SEBANYAK <STRONG>RM </STRONG>…............................ (<STRONG>RINGGIT MALAYSIA</STRONG> ….................................…… DAN <STRONG>SEN</STRONG> …..) (FOB).</P><P CLASS="QL-ALIGN-JUSTIFY">&NBSP;</P><P CLASS="QL-ALIGN-JUSTIFY">3.&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;JIKA SEBUT HARGA INI DITERIMA, SAYA/KAMI BERSETUJU UNTUK MENANDATANGANI SURAT PERJANJIAN DAN BERSETUJU UNTUK MEMBERI <STRONG>BON PELAKSANAAN</STRONG> DALAM TEMPOH MASA <STRONG>EMPAT BELAS (14) HARI</STRONG> DARI TARIKH SURAT SETUJU TERIMA TAWARAN.</P><P CLASS="QL-ALIGN-JUSTIFY">&NBSP;</P><P CLASS="QL-ALIGN-JUSTIFY">4.&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;APA-APA PERTIKAIAN DENGAN SYARAT-SYARAT TENDER INI AKAN DIRUJUK KEPADA PENIMBANGTARA DAN AKAN TERTAKLUK KEPADA UNDANG-UNDANG MALAYSIA.</P><P CLASS="QL-ALIGN-JUSTIFY">&NBSP;</P><P CLASS="QL-ALIGN-JUSTIFY">&NBSP;</P><P CLASS="QL-ALIGN-JUSTIFY">5.&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;SAYA/KAMI BERSETUJU BAHAWA TEMPOH SAH LAKU TENDER INI AKAN DIBUKA SELAMA <STRONG>180 HARI</STRONG> DARIPADA TARIKH TENDER INI DITUTUP DAN DALAM TEMPOH TERSEBUT SAYA/KAMI TIDAK BOLEH MENARIK BALIK TAWARAN TENDER TERSEBUT.</P><P CLASS="QL-ALIGN-JUSTIFY">&NBSP;</P><P CLASS="QL-ALIGN-JUSTIFY">6.&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;SAYA/KAMI JUGA TELAH MEMAHAMI BAHAWA PEJABAT LEMBAGA BERHAK MENERIMA ATAU MENOLAK TENDER INI, SAMA ADA HARGA YANG DITAWARKAN RENDAH ATAU TINGGI ATAU SAMA DENGAN HARGA PETENDER-PETENDER LAIN.</P><P CLASS="QL-ALIGN-JUSTIFY">&NBSP;</P><P CLASS="QL-ALIGN-JUSTIFY">7.&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;SAYA/KAMI JUGA MENGESAHKAN, TELAH MENYEMAK SENDIRI SEMUA DOKUMEN YANG DIGUNAKAN UNTUK TENDER INI ADALAH YANG SEBENAR YANG TERDAPAT DI DALAM DOKUMEN TENDER YANG DITERIMA OLEH SYARIKAT.</P><P CLASS="QL-ALIGN-JUSTIFY">&NBSP;</P><P CLASS="QL-ALIGN-JUSTIFY">&NBSP;</P><P CLASS="QL-ALIGN-JUSTIFY">&NBSP;</P><P CLASS="QL-ALIGN-JUSTIFY">&NBSP;</P><P CLASS="QL-ALIGN-JUSTIFY">……………………….………….….&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;…………………………………..</P><P CLASS="QL-ALIGN-JUSTIFY">(TANDATANGAN PETENDER)&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;(TANDATANGAN SAKSI)</P><P CLASS="QL-ALIGN-JUSTIFY">NAMA PENUH :&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;NAMA PENUH :</P><P CLASS="QL-ALIGN-JUSTIFY">NO. K/P&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;:&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;NO. K/P&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;:</P><P CLASS="QL-ALIGN-JUSTIFY">ALAMAT&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;:&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;ALAMAT&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;:&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;</P><P CLASS="QL-ALIGN-JUSTIFY">&NBSP;</P><P CLASS="QL-ALIGN-JUSTIFY">&NBSP;</P><P CLASS="QL-ALIGN-JUSTIFY">&NBSP;</P><P CLASS="QL-ALIGN-JUSTIFY">&NBSP;</P><P CLASS="QL-ALIGN-JUSTIFY">&NBSP;</P><P CLASS="QL-ALIGN-JUSTIFY">&NBSP;</P><P CLASS="QL-ALIGN-JUSTIFY">NO. TELEFON&NBSP;&NBSP;:&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;NO. TELEFON&NBSP;&NBSP;:</P><P CLASS="QL-ALIGN-JUSTIFY">NO. FAX&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;:&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;NO. FAX&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;:</P><P CLASS="QL-ALIGN-JUSTIFY">TARIKH&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;:&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;TARIKH&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;:</P><P CLASS="QL-ALIGN-JUSTIFY"><U>&NBSP;</U></P><P CLASS="QL-ALIGN-JUSTIFY"><U>&NBSP;</U></P><P CLASS="QL-ALIGN-JUSTIFY"><U>&NBSP;</U></P><P CLASS="QL-ALIGN-JUSTIFY">CAP RASMI SYARIKAT&NBSP;:</P><H5><BR></H5>',
                'CAS_LETTER_ID' => 6,
                'CAS_LETTER_TITTLE' => 'SUSPENSION LETTER',
                'CREATE_BY' => NULL,
            ),
            2 => 
            array (
            'CAS_LETTER_DESC' => '<P><BR></P><P><STRONG>SURAT AKUAN PETENDER</STRONG></P><P><STRONG>&AMP;NBSP;</STRONG></P><P><STRONG>NO. TENDER : LKPU (S) 2/2020</STRONG></P><P><BR></P><P>KEPADA:</P><P><BR></P><P>LEMBAGA KELAYAKAN PROFESION UNDANG-UNDANG MALAYSIA</P><P>UNIT 22-01, ARAS 2, MENARA 2</P><P>MENARA KEMBAR BANK RAKYAT,</P><P>NO. 33, JALAN RAKYAT,</P><P>50470 KUALA LUMPUR,</P><P>WILAYAH PERSEKUTUAN KUALA LUMPUR</P><P><BR></P><P>TUAN,</P><P><BR></P><P><STRONG>MELAKSANAKAN KAJIAN KEPERLUAN PENGGUNA, ANALISIS DAN REKA BENTUK, PEMBANGUNAN, PENGUJIAN, LATIHAN, DAN PENYENGGARAAN PERISIAN DAN APLIKASI&AMP;NBSP;UNTUK SISTEM PENGURUSAN PEPERIKSAAN LEMBAGA KELAYAKAN PROFESION UNDANG-UNDANG, MALAYSIA (E-LPQB).</STRONG></P><P><BR></P><P>SAYA/KAMI YANG MENURUNKAN TANDATANGAN DI BAWAH DENGAN INI MENGAMBIL BAHAGIAN UNTUK <STRONG STYLE="COLOR: RGB(0, 0, 204); BACKGROUND-COLOR: YELLOW;">&AMP;NBSP;MELAKSANAKAN KAJIAN KEPERLUAN PENGGUNA, ANALISIS DAN REKA BENTUK, PEMBANGUNAN, PENGUJIAN, LATIHAN, DAN PENYENGGARAAN PERISIAN DAN APLIKASI&AMP;NBSP;UNTUK SISTEM PENGURUSAN PEPERIKSAAN LEMBAGA KELAYAKAN PROFESION UNDANG-UNDANG, MALAYSIA (E-LPQB) </STRONG>SEPERTI YANG DINYATAKAN DI DALAM LAMPIRAN D-3 – JADUAL HARGA DAN BERSETUJU UNTUK MENERIMA SERTA MEMATUHI DAN TERIKAT DENGAN SEMUA ARAHAN DAN SYARAT-SYARAT KEPADA PENYEBUT HARGA, KONTRAK DAN SPESIFIKASI YANG TERKANDUNG DALAM DOKUMEN TENDER YANG DIKEMBARKAN BERSAMA DENGAN TAWARAN INI.</P><P><BR></P><P>2. ADALAH SAYA/KAMI DENGAN INI MENAWARKAN APLIKASI TERSEBUT BAGI JUMLAH KESELURUHAN SEBANYAK <STRONG>RM </STRONG>…............................ (<STRONG>RINGGIT MALAYSIA</STRONG> ….................................…… DAN <STRONG>SEN</STRONG> …..) (FOB).</P><P><BR></P><P>3. JIKA SEBUT HARGA INI DITERIMA, SAYA/KAMI BERSETUJU UNTUK MENANDATANGANI SURAT PERJANJIAN DAN BERSETUJU UNTUK MEMBERI <STRONG>BON PELAKSANAAN</STRONG> DALAM TEMPOH MASA <STRONG>EMPAT BELAS (14) HARI</STRONG> DARI TARIKH SURAT SETUJU TERIMA TAWARAN.</P><P>&AMP;NBSP;</P><P>4.			APA-APA PERTIKAIAN DENGAN SYARAT-SYARAT TENDER INI AKAN DIRUJUK KEPADA PENIMBANGTARA DAN AKAN TERTAKLUK KEPADA UNDANG-UNDANG MALAYSIA.</P><P>&AMP;NBSP;</P><P>&AMP;NBSP;</P><P>5.&AMP;NBSP;&AMP;NBSP;&AMP;NBSP;&AMP;NBSP;&AMP;NBSP;SAYA/KAMI BERSETUJU BAHAWA TEMPOH SAH LAKU TENDER INI AKAN DIBUKA SELAMA <STRONG>180 HARI</STRONG> DARIPADA TARIKH TENDER INI DITUTUP DAN DALAM TEMPOH TERSEBUT SAYA/KAMI TIDAK BOLEH MENARIK BALIK TAWARAN TENDER TERSEBUT.</P><P><BR></P><P>6.			SAYA/KAMI JUGA TELAH MEMAHAMI BAHAWA PEJABAT LEMBAGA BERHAK MENERIMA ATAU MENOLAK TENDER INI, SAMA ADA HARGA YANG DITAWARKAN RENDAH ATAU TINGGI ATAU SAMA DENGAN HARGA PETENDER-PETENDER LAIN.</P><P><BR></P><P>7.&AMP;NBSP;&AMP;NBSP;&AMP;NBSP;&AMP;NBSP;&AMP;NBSP;SAYA/KAMI JUGA MENGESAHKAN, TELAH MENYEMAK SENDIRI SEMUA DOKUMEN YANG DIGUNAKAN UNTUK TENDER INI ADALAH YANG SEBENAR YANG TERDAPAT DI DALAM DOKUMEN TENDER YANG DITERIMA OLEH SYARIKAT.</P><P><BR></P><P><BR></P><P>……………………….………….….</P><P>(TANDATANGAN SAKSI)</P><P>NAMA PENUH NAMA PENUH :</P><P>NO.</P><P>CAP RASMI SYARIKAT&AMP;NBSP;:</P><H5><BR></H5><H5><BR></H5>',
                'CAS_LETTER_ID' => 7,
                'CAS_LETTER_TITTLE' => 'SUSPENTION 2',
                'CREATE_BY' => NULL,
            ),
            3 => 
            array (
                'CAS_LETTER_DESC' => '<h5>BHBWDBWq</h5>',
                'CAS_LETTER_ID' => 11,
                'CAS_LETTER_TITTLE' => 'MJBDJHAJ',
                'CREATE_BY' => NULL,
            ),
            4 => 
            array (
                'CAS_LETTER_DESC' => '<H1>YOU ARE HEREBY BARRED </H1><P><BR></P><P>AS PER TITLE YOU ARE HEREBY BARRED FROM THIS ORGANIZATION</P>',
                'CAS_LETTER_ID' => 16,
                'CAS_LETTER_TITTLE' => 'BARRED LETTER',
                'CREATE_BY' => NULL,
            ),
            5 => 
            array (
                'CAS_LETTER_DESC' => '<H5>CREATOR</H5>',
                'CAS_LETTER_ID' => 17,
                'CAS_LETTER_TITTLE' => 'WITH BY',
                'CREATE_BY' => 7,
            ),
            6 => 
            array (
                'CAS_LETTER_DESC' => '<H1>YOU ARE TERMINATED </H1>',
                'CAS_LETTER_ID' => 18,
                'CAS_LETTER_TITTLE' => 'TERMINATE',
                'CREATE_BY' => 84,
            ),
            7 => 
            array (
                'CAS_LETTER_DESC' => '<H5>HELLO</H5>',
                'CAS_LETTER_ID' => 19,
                'CAS_LETTER_TITTLE' => 'HELLO',
                'CREATE_BY' => 84,
            ),
            8 => 
            array (
                'CAS_LETTER_DESC' => '<H5>TEST</H5>',
                'CAS_LETTER_ID' => 20,
                'CAS_LETTER_TITTLE' => 'TEST',
                'CREATE_BY' => 7,
            ),
        ));
        
        
    }
}