<?php
/**
 * Module & Controller Generator
 *
 * INSTRUCTIONS!
 * Please read the example, and key in the models in the provided array section.
 *
 * If table name are EXAMPLE_TABLE, please key in ExampleTable
 *
 * Example :
 * $model = array(
 *   'ExampleTable',
 *   'ExampleTable1'
 * );
 *
 * Code above will generate model and controller for EXAMPLE_TABLE & EXAMPLE_TABLE1
 */
$model = array(
    'AuditTrails',
    'CpdWaiverReason',
    'CpdRenewalCalc',
    'ConsultantAppeal',
    'FmsCutoffTime',
    'FmsFundcategory',
    // 'FmsFundgroup',
    'FmsFundtype',
    'ManageModule',
    'ManageDepartment',
    'ManageGroup',
    'ManageDivision',
    'ManageFormTemplate',
    'ManageEvent',
    'ManageAnnouncement',
    'ManageEventDocument',
    'ManageEventApproval',
    'ManageScreen',
    'ManageScreenAccess',
    'SettingEmail',
    'SettingGeneral',
    'SettingLdap',
    'SettingPayment',
    'SettingCalendar',
    'UserAddress',
    'SettingEmailTemplate',
    'DistributorType',
    'FinanceAccCode',
    'FinanceAccGlcode',
    'FinanceFeeAmount',
    'ManageSubmodule',
    'SettingSms',
    'ManageSubmodule',
    'SettingEmailTemplate',
    'ConsultantQualification',
    'ConsultantDesignationExemption',
    'ConsultantAppealExamination',
    'ConsultantType',
    'ManageRequiredDocument',
    'ManageRequiredDocument',
    'DistributorType',
    'ConsultantType',
    'SettingPostal',
    'SettingCity',
    'SmsLog',
    'SmsTac',
    'SettingDashboardChart',
    'ApprovalLevel',
    'Notification',
    'SettingPassword',
    'SettingUserid',
    'ApprovalLevel',
    'SettingPassword',
    'CpdRuleCalc',
    'CpdSetting',
    'CpdCutOffDate',
    'ConsultantFee',
    'AnnualFeeInvoice',
    'FmsUmbrellaFund',
    'LoginSetting',
    'SystemBlockDuration',
    'LoginIdleSession',
    'PasswordHistory',
    'PasswordDefault',
    'DistributorManageGroup',
    'DistributorManageModule',
    'DistributorManageSubmodule',
    'DistributorManageScreen',
    'ConsultantManageGroup',
    'ConsultantManageModule',
    'ConsultantManageSubmodule',
    'ConsultantManageScreen',
    'ThirdpartyManageGroup',
    'ThirdpartyManageModule',
    // 'ThirdpartyManageSubmodule',
    // 'ThirdPartyManageScreen',
    'TpManageGroup',
    'TpManageModule',
    'TpManageSubmodule',
    'TpManageScreen',
    'ConsultantAppeal',
    'DistributorScreenAccess',
    'DistributorApprovalLevel',
 
);
