<?php
namespace App\Reports;
class DistributorInformationReportPDF extends \koolreport\KoolReport
{
    use \koolreport\laravel\Friendship;
    use \koolreport\clients\FontAwesome;
    use \koolreport\amazing\Theme;
    use \koolreport\export\Exportable;
    use \koolreport\excel\ExcelExportable;
    use \koolreport\inputs\Bindable;
    use \koolreport\inputs\POSTBinding;
    //use \koolreport\cloudexport\Exportable;
    function defaultParamValues()
    {
        $start_date = date('Y-m-d');
       $end_date = date('Y-m-d');
        return array(
            "dateRange"=>array(
                $start_date,
                $end_date
            ),
            "SETTINGID"=>0,
            "BUSINESSTYPE" => 0,
            "DISTRIBUTORIDS" => array(0),
            "DISTIDS" => array(0),
        );
    }
    function bindParamsToInputs()
    {
        return array(
          "dateRange"=>"dateRange",
           "DISTRIBUTORIDS" => "DISTRIBUTORIDS",
           "DISTIDS" => "DISTIDS",
           "SETTINGID",
           "BUSINESSTYPE",
        );
    }
    function setup()
    {
      $query_params = array();
      $query_params1 = array();
      $query_params2 = array();
      if($this->params["DISTRIBUTORIDS"] != array(0) )
      {
          $query_params[":DISTRIBUTOR_ID"] = $this->params["DISTRIBUTORIDS"];
      }
      if($this->params["DISTIDS"] != array(0) )
      {
          $query_params[":DISTRIBUTOR_TYPE_ID"] = $this->params["DISTIDS"];
      }
      if($this->params["SETTINGID"] != 0)
      {
          $query_params[":SET_ID"] = $this->params["SETTINGID"];
      }
      if($this->params["BUSINESSTYPE"] != 0)
      {
          $query_params[":BUSINESS_TYPE"] = $this->params["BUSINESSTYPE"];
      }
        $this->src("mysql")
        ->query("Select DISTRIBUTOR.DISTRIBUTOR_ID AS DID,DISTRIBUTOR.DIST_NAME AS DIST_NAME,DISTRIBUTOR.DIST_CODE AS DIST_CODE,CONCAT_WS(', ',DISTRIBUTOR.DIST_REGI_NUM1, DISTRIBUTOR. 	DIST_REGI_NUM2) AS REGNUM,DISTRIBUTOR.DIST_DATE_INCORP AS DIST_DATE_INCORP,DISTRIBUTOR.DIST_TYPE_SETUP AS DIST_TYPE_SETUP,DISTRIBUTOR.DIST_PHONE_NUMBER AS DIST_PHONE_NUMBER,DISTRIBUTOR.DIST_PHONE_EXTENSION AS DIST_PHONE_EXTENSION,DISTRIBUTOR.DIST_MOBILE_NUMBER AS DIST_MOBILE_NUMBER,DISTRIBUTOR.DIST_FAX_NUMBER AS DIST_FAX_NUMBER,DISTRIBUTOR.DIST_EMAIL AS DIST_EMAIL,DISTRIBUTOR.DIST_COMPANY_WEBSITE AS DIST_COMPANY_WEBSITE,DISTRIBUTOR.CREATE_TIMESTAMP AS CREATE_TIMESTAMP,CONCAT_WS(', ',DISTRIBUTOR_ADDRESS.DIST_ADDR_1,DISTRIBUTOR_ADDRESS.DIST_ADDR_2,DISTRIBUTOR_ADDRESS.DIST_ADDR_3) AS ADDRESS,SETTING_POSTAL.POSTCODE_NO AS POSTCODE_NO,SETTING_CITY.SET_CITY_NAME AS SET_CITY_NAME,SETTING_GENERAL.SET_PARAM AS STATE,DISTRIBUTOR_LEDGER.DIST_ACC_AMOUNT AS DIST_ACC_AMOUNT,DISTRIBUTOR_DETAIL_INFO.DIST_TYPE_STRUCTURE AS DIST_TYPE_STRUCTURE,DISTRIBUTOR_DETAIL_INFO.DIST_NUM_DIST_POINT AS DIST_NUM_DIST_POINT,ARDATA.REPR_NAME AS AR_NAME,AR_SALUTATION.USER_SAL_NAME AS AR_SALUT,ARDATA.REPR_POSITION AS AR_POSITION,ARDATA.REPR_MOBILE_NUMBER AS AR_MOBILE_NUMBER,ARDATA.REPR_EMAIL AS AR_EMAIL,AARDATA.REPR_NAME AS AAR_NAME,AAR_SALUTATION.USER_SAL_NAME AS AAR_SALUT,AARDATA.REPR_POSITION AS AAR_POSITION,AARDATA.REPR_MOBILE_NUMBER AS AAR_MOBILE_NUMBER,AARDATA.REPR_EMAIL AS AAR_EMAIL,COMPLIANCEDATA.ADD_NAME AS COM_NAME,COMPLIANCE_SALUTATION.USER_SAL_NAME AS COM_SALUT,COMPLIANCEDATA.ADD_MOBILE_NUMBER AS COM_MOBILE_NUMBER,COMPLIANCEDATA.ADD_EMAIL AS COM_EMAIL,HODUTSDATA.ADD_NAME AS UTS_NAME,HODUTS_SALUTATION.USER_SAL_NAME AS UTS_SALUT,HODUTSDATA.ADD_MOBILE_NUMBER AS UTS_MOBILE_NUMBER,HODUTSDATA.ADD_EMAIL AS UTS_EMAIL,HODPRSDATA.ADD_NAME AS PRS_NAME,HODPRS_SALUTATION.USER_SAL_NAME AS PRS_SALUT,HODPRSDATA.ADD_MOBILE_NUMBER AS PRS_MOBILE_NUMBER,HODPRSDATA.ADD_EMAIL AS PRS_EMAIL,HODTRAINDATA.ADD_NAME AS TRAIN_NAME,HODTRAIN_SALUTATION.USER_SAL_NAME AS TRAIN_SALUT,HODTRAINDATA.ADD_MOBILE_NUMBER AS TRAIN_MOBILE_NUMBER,HODTRAINDATA.ADD_EMAIL AS TRAIN_EMAIL
        from distributor_management.DISTRIBUTOR AS DISTRIBUTOR
        LEFT JOIN distributor_management.DISTRIBUTOR_ADDRESS AS DISTRIBUTOR_ADDRESS
        ON DISTRIBUTOR_ADDRESS.DIST_ID = DISTRIBUTOR.DISTRIBUTOR_ID
        LEFT JOIN admin_management.SETTING_POSTAL AS SETTING_POSTAL
        ON SETTING_POSTAL.SETTING_POSTCODE_ID = DISTRIBUTOR_ADDRESS.DIST_POSTAL
        LEFT JOIN admin_management.SETTING_CITY AS SETTING_CITY
        ON SETTING_CITY.SETTING_CITY_ID = DISTRIBUTOR_ADDRESS.DIST_CITY
        LEFT JOIN admin_management.SETTING_GENERAL AS SETTING_GENERAL
        ON SETTING_GENERAL.SETTING_GENERAL_ID = DISTRIBUTOR_ADDRESS.DIST_STATE
        LEFT JOIN distributor_management.DISTRIBUTOR_LEDGER AS DISTRIBUTOR_LEDGER
        ON DISTRIBUTOR_LEDGER.DIST_ID = DISTRIBUTOR.DISTRIBUTOR_ID
        LEFT JOIN distributor_management.DISTRIBUTOR_DETAIL_INFO AS DISTRIBUTOR_DETAIL_INFO
        ON DISTRIBUTOR_DETAIL_INFO.DIST_ID = DISTRIBUTOR.DISTRIBUTOR_ID
        LEFT JOIN distributor_management.DISTRIBUTOR_REPRESENTATIVE AS ARDATA
        ON ARDATA.DIST_ID = DISTRIBUTOR.DISTRIBUTOR_ID AND ARDATA.REPR_TYPE = 'AR'
        LEFT JOIN distributor_management.USER_SALUTATION AS AR_SALUTATION
        ON AR_SALUTATION.USER_SAL_ID = ARDATA.REPR_SALUTATION
        LEFT JOIN distributor_management.DISTRIBUTOR_REPRESENTATIVE AS AARDATA
        ON AARDATA.DIST_ID = DISTRIBUTOR.DISTRIBUTOR_ID AND AARDATA.REPR_TYPE = 'AAR'
        LEFT JOIN distributor_management.USER_SALUTATION AS AAR_SALUTATION
        ON AAR_SALUTATION.USER_SAL_ID = AARDATA.REPR_SALUTATION
        LEFT JOIN distributor_management.DISTRIBUTOR_ADDITIONAL_INFO AS COMPLIANCEDATA
        ON COMPLIANCEDATA.DIST_ID = DISTRIBUTOR.DISTRIBUTOR_ID AND COMPLIANCEDATA.ADD_TYPE = 'HOD_COMPL'
        LEFT JOIN distributor_management.USER_SALUTATION AS COMPLIANCE_SALUTATION
        ON COMPLIANCE_SALUTATION.USER_SAL_ID = COMPLIANCEDATA.ADD_SALUTATION
        LEFT JOIN distributor_management.DISTRIBUTOR_ADDITIONAL_INFO AS HODUTSDATA
        ON HODUTSDATA.DIST_ID = DISTRIBUTOR.DISTRIBUTOR_ID AND HODUTSDATA.ADD_TYPE = 'HOD_UTS'
        LEFT JOIN distributor_management.USER_SALUTATION AS HODUTS_SALUTATION
        ON HODUTS_SALUTATION.USER_SAL_ID = HODUTSDATA.ADD_SALUTATION
        LEFT JOIN distributor_management.DISTRIBUTOR_ADDITIONAL_INFO AS HODPRSDATA
        ON HODPRSDATA.DIST_ID = DISTRIBUTOR.DISTRIBUTOR_ID AND HODPRSDATA.ADD_TYPE = 'HOD_PRS'
        LEFT JOIN distributor_management.USER_SALUTATION AS HODPRS_SALUTATION
        ON HODPRS_SALUTATION.USER_SAL_ID = HODPRSDATA.ADD_SALUTATION
        LEFT JOIN distributor_management.DISTRIBUTOR_ADDITIONAL_INFO AS HODTRAINDATA
        ON HODTRAINDATA.DIST_ID = DISTRIBUTOR.DISTRIBUTOR_ID AND HODTRAINDATA.ADD_TYPE = 'HOD_TRAIN'
        LEFT JOIN distributor_management.USER_SALUTATION AS HODTRAIN_SALUTATION
        ON HODTRAIN_SALUTATION.USER_SAL_ID = HODTRAINDATA.ADD_SALUTATION
        LEFT JOIN distributor_management.DISTRIBUTOR_TYPE AS DISTRIBUTOR_TYPE
        ON DISTRIBUTOR_TYPE.DIST_ID = DISTRIBUTOR.DISTRIBUTOR_ID
        WHERE 1 = 1
        ".(($this->params["DISTRIBUTORIDS"]!=array(0))?"and DISTRIBUTOR.DISTRIBUTOR_ID in ( :DISTRIBUTOR_ID)":"")."
        ".(($this->params["DISTIDS"]!=array(0))?"and DISTRIBUTOR_TYPE.DIST_TYPE in ( :DISTRIBUTOR_TYPE_ID)":"")."
        ".(($this->params["SETTINGID"]!= 0)?"and  DISTRIBUTOR_ADDRESS.DIST_STATE = :SET_ID":"")."
        ".(($this->params["BUSINESSTYPE"]!= 0)?"and DISTRIBUTOR_DETAIL_INFO.DIST_TYPE_STRUCTURE = :BUSINESS_TYPE":"")."
        GROUP BY DID order by DID asc")
        ->params($query_params)
        ->pipe($this->dataStore("DISTRIBUTORINFORMATIONREPORT"));

        $this->src("mysql")
        ->query("select CONSULTANT_LICENSE.CONSULTANT_ID AS CONID,CONSULTANT_LICENSE.CONSULTANT_TYPE_ID AS TID,SETTING.SET_PARAM AS STATUSTAG,CONSULTANT_LICENSE.TS_ID AS TS_ID
        from consultant_management.CONSULTANT_LICENSE AS CONSULTANT_LICENSE
        LEFT JOIN admin_management.SETTING_GENERAL AS SETTING
        ON SETTING.SETTING_GENERAL_ID = CONSULTANT_LICENSE.CONSULTANT_STATUS 
        ")
        ->pipe($this->dataStore("CONSULTANTLICENSE"));

        $this->src("mysql")
        ->query("select CONSULTANT_TYPE.CONSULTANT_TYPE_ID AS SCHEMEID,CONSULTANT_TYPE.TYPE_SCHEME AS TYPE_SCHEME
        from admin_management.CONSULTANT_TYPE AS CONSULTANT_TYPE
        ")
        ->pipe($this->dataStore("CONSULTANTSCHEME"));

        $this->src("mysql")
        ->query("select SETTING.SETTING_GENERAL_ID AS SETTINGID,SETTING.SET_PARAM AS PARAM
        from admin_management.SETTING_GENERAL AS SETTING where SET_TYPE LIKE '%CLASSIFICATION%'
        ")
        ->pipe($this->dataStore("CONSULTANTSTATUS"));
        $this->src("mysql")
        ->query("select DISTRIBUTOR.DISTRIBUTOR_ID AS DISTRIBUTORID,DISTRIBUTOR.DIST_NAME AS DIST_NAME
        from distributor_management.DISTRIBUTOR AS DISTRIBUTOR
        ")
        ->pipe($this->dataStore("CONSULTANTDISTRIBUTOR"));

        $this->src("mysql")
        ->query("select DISTRIBUTOR_TYPE.DIST_ID AS DIST_ID,DISTRIBUTORTYPE.DIST_TYPE_NAME AS DIST_TYPE_NAME
        from distributor_management.DISTRIBUTOR_TYPE AS DISTRIBUTOR_TYPE
        LEFT JOIN admin_management.DISTRIBUTOR_TYPE AS DISTRIBUTORTYPE
        ON DISTRIBUTORTYPE.DISTRIBUTOR_TYPE_ID = DISTRIBUTOR_TYPE.DIST_TYPE
        ")
        ->pipe($this->dataStore("DISTRIBUTORTYPE"));

        $this->src("mysql")
        ->query("select DISTRIBUTORTYPE.DISTRIBUTOR_TYPE_ID AS DISTID,DISTRIBUTORTYPE.DIST_TYPE_NAME AS DIST_TYPE_NAME
        from admin_management.DISTRIBUTOR_TYPE AS DISTRIBUTORTYPE
        ")
        ->pipe($this->dataStore("DISTRIBUTORTYPELIST"));

        $this->src("mysql")
        ->query("select STATE.SETTING_GENERAL_ID AS SETTING_GENERAL_ID,STATE.SET_PARAM AS SET_PARAM
        from admin_management.SETTING_GENERAL AS STATE
        where SET_TYPE = 'STATE'
        ")
        ->pipe($this->dataStore("STATELIST"));
  }
}
