<?php
namespace App\Reports;
class FundDataAllReportPDF extends \koolreport\KoolReport
{
    use \koolreport\laravel\Friendship;
    use \koolreport\clients\FontAwesome;
    use \koolreport\amazing\Theme;
    use \koolreport\export\Exportable;
    use \koolreport\excel\ExcelExportable;
    use \koolreport\inputs\Bindable;
    use \koolreport\inputs\POSTBinding;
    //use \koolreport\cloudexport\Exportable;
    function defaultParamValues()
    {
          // $start_date =  "";//date('Y-m-d', strtotime('first day of january last year'));
          // $end_date = ""; //date('Y-m-d', strtotime('last day of december this year'));
        return array(
            // "dateRange"=>array(
            //     $start_date,
            //     $end_date
            // ),
            "DISTRIBUTORIDS" => array(0),
           // "TSIDS" => array(0),
           // "SCHEMEIDS" => array(0),
           // "SHARIAH" => array(1,2),
        );
    }
    function bindParamsToInputs()
    {
        return array(
         // "dateRange"=>"dateRange",
         "DISTRIBUTORIDS" => "DISTRIBUTORIDS",
        // "TSIDS" => "TSIDS",
        // "SCHEMEIDS" => "SCHEMEIDS",
       //  "SHARIAH" => "SHARIAH",
        );
    }
    function setup()
    {
      $query_params = array();
      $query_params1 = array();
      $query_params2 = array();
        // if(isset($this->params["dateRange"][0]))
        // {
        // $query_params[":start"] = $this->params["dateRange"][0];
        // }
        // if(isset($this->params["dateRange"][1]))
        // {
        // $query_params[":end"] = $this->params["dateRange"][1];
        // }
        if($this->params["DISTRIBUTORIDS"] != array(0) )
        {
        $query_params[":DISTRIBUTOR_ID"] = $this->params["DISTRIBUTORIDS"];
        }
        // if($this->params["TSIDS"] != array(0) )
        // {
        // $query_params[":TS_ID"] = $this->params["TSIDS"];
        // }
        $this->src("mysql")
        ->query("Select DISTRIBUTOR.DIST_NAME AS DIST_NAME,FUND_PROFILE.FUND_NAME AS FUND_NAME,FUND_PROFILE.FUND_CODE_FIMM AS FUND_CODE_FIMM,FUND_PROFILE.FUND_MATURITY_CLOSURE_DATE AS FUND_MATURITY_CLOSURE_DATE,FUND_PROFILE.FUND_DATE_LAUNCH AS LAUNCHDATE,FUND_PROFILE.FUND_SUSPENSION_DATE AS FUND_SUSPENSION_DATE,TASK_STATUS.TS_PARAM AS TS_PARAM,USER.USER_NAME AS USER_NAME,DISTRIBUTOR_MANAGE_GROUP.DISTRIBUTOR_MANAGE_GROUP_NAME AS GROUPNAME,FUND_PROFILE.FUND_UMBRELLA AS UMBRELLACODE,FUND_PROFILE.FUND_CODE_MEMBER AS MEMBERCODE,FUND_PROFILE.FUND_PREVIOUS_NAME AS FORMERNAME,FUND_PROFILE.FUND_NAME_SHORT AS SHORTNAME,FUND_PROFILE.FUND_NAME_CHINESE AS CHINESENAME,FMS_FUNDTYPE.FUND_NAME AS FUNDTYPE,FMS_FUNDCATEGORY.GROUP_ASSET AS GROUP_ASSET,FMS_FUND_DOMICILE.FUND_DOMICILE_NAME AS FUND_DOMICILE_NAME,FUND_PROFILE.FUND_DATE_EXPIRY AS FUND_DATE_EXPIRY,SETTING_GENERAL.SET_PARAM AS CURRENCY,FUND_PROFILE.FUND_SUB_MANAGER AS FUND_SUB_MANAGER,FUND_PROFILE.FUND_SYARIAH_COMP AS FUND_SYARIAH_COMP,FUND_PROFILE.FUND_ANNUAL_MGMT AS FUND_ANNUAL_MGMT,FUND_PROFILE.FUND_FUND_PERFORMANCE AS FUND_FUND_PERFORMANCE,FUND_PROFILE.FUND_STATUS_EPF AS FUND_STATUS_EPF,FUND_PROFILE.FUND_EPF_CODE AS FUND_EPF_CODE,FUND_PROFILE.FUND_DAILY_NAV AS FUND_DAILY_NAV,FUND_PROFILE.FUND_FEE_ANNUAL AS FUND_FEE_ANNUAL,FUND_PROFILE.FUND_FEE_PERFORMANCE AS FUND_FEE_PERFORMANCE,FUND_PROFILE.FUND_STATUS_RATIO AS FUND_STATUS_RATIO,FUND_PROFILE.FUND_RATIO AS FUND_RATIO,FUND_PROFILE.FUND_HURDLE AS FUND_HURDLE,FUND_PROFILE.FUND_HURDLE_STATUS AS FUND_HURDLE_STATUS,FUND_PROFILE.FUND_STATUS_HURDLE_RATE AS FUND_STATUS_HURDLE_RATE,FUND_PROFILE.FUND_PRICE_PERUNIT AS FUND_PRICE_PERUNIT,FUND_PROFILE.FUND_YEAR_END AS FUND_YEAR_END,FUND_PROFILE.FUND_SALES_CHARGE AS FUND_SALES_CHARGE,FMS_SCHEME_STRUCTURE.FMS_SCHEME_NAME AS FMS_SCHEME_NAME,FUND_PROFILE.FUND_FOCUS AS FUND_FOCUS,FUND_PROFILE.FUND_WHOLESALE AS FUND_WHOLESALE,FUND_PROFILE.FUND_FEEDER AS FUND_FEEDER,FUND_PROFILE.FUND_FEEDER_STATUS AS FUND_FEEDER_STATUS,FUND_PROFILE.FUND_ISIN AS FUND_ISIN,FUND_PROFILE.FUND_SC_CODE AS FUND_SC_CODE,FUND_PROFILE.FUND_LIPPER_CODE AS FUND_LIPPER_CODE,FUND_PROFILE.FUND_NAME_CHANGE_DATE AS FUND_NAME_CHANGE_DATE,FUND_PROFILE.FUND_STATUS_MER AS FUND_STATUS_MER,FUND_PROFILE.FUND_MER AS FUND_MER,FUND_PROFILE.FUND_PERFORMANCE_FEE_STATUS AS FUND_PERFORMANCE_FEE_STATUS,FUND_PROFILE.FUND_REACTIVATION_DATE AS FUND_REACTIVATION_DATE,FUND_PROFILE.FUND_FINANCIAL_YEAR_END AS FUND_FINANCIAL_YEAR_END,FUND_PROFILE.FUND_STATUS_ANNUAL_MGMT AS FUND_STATUS_ANNUAL_MGMT,FUND_PROFILE.FUND_STATUS_FEE_PERFORMANCE AS FUND_STATUS_FEE_PERFORMANCE,FUND_PROFILE.FUND_NOTES_ID AS FUND_NOTES_ID,FUND_PROFILE.FUND_STATUS_SALE_CHARGE AS FUND_STATUS_SALE_CHARGE,FUND_PROFILE.FUND_STATUS_MINIMUM_SALE_CHARGE AS FUND_STATUS_MINIMUM_SALE_CHARGE,FUND_PROFILE.FUND_STATUS_MAXIMUM_SALE_CHARGE AS FUND_STATUS_MAXIMUM_SALE_CHARGE,FUND_PROFILE.FUND_MINIMUM_SALE_CHARGE AS FUND_MINIMUM_SALE_CHARGE,FUND_PROFILE.FUND_MAXIMUM_SALE_CHARGE AS FUND_MAXIMUM_SALE_CHARGE,FUND_PROFILE.FUND_UNIT_STRUCTURE AS FUND_UNIT_STRUCTURE,FUND_PROFILE.FUND_INVESTMENT_FOCUS AS FUND_INVESTMENT_FOCUS,FUND_PROFILE.FUND_FOF_STATUS AS FUND_FOF_STATUS,FUND_PROFILE.FUND_FOF AS FUND_FOF,FUND_PROFILE.FUND_UCITS_STATUS AS FUND_UCITS_STATUS,FUND_PROFILE.FUND_UCITS AS FUND_UCITS,FUND_PROFILE.FUND_ASEAN_CIS_STATUS AS FUND_ASEAN_CIS_STATUS,FUND_PROFILE.FUND_ASEAN_CIS AS FUND_ASEAN_CIS,FUND_PROFILE.FUND_STATUS_SRI_ESG AS FUND_STATUS_SRI_ESG,FUND_PROFILE.FUND_SRI_ESG AS FUND_SRI_ESG,FUND_PROFILE.FUND_DATE_SRI_ESG_EFFECTIVE_DATE AS FUND_DATE_SRI_ESG_EFFECTIVE_DATE,FUND_PROFILE.FUND_NON_MEMBER AS FUND_NON_MEMBER,FUND_PROFILE.FUND_DEFINITION AS FUND_DEFINITION,FUND_PROFILE.FUND_UNITS AS FUND_UNITS,FUND_PROFILE.CREATE_TIMESTAMP AS CREATE_TIMESTAMP
        from funds_management.FUND_PROFILE AS FUND_PROFILE
        LEFT JOIN distributor_management.DISTRIBUTOR AS DISTRIBUTOR
        ON DISTRIBUTOR.DISTRIBUTOR_ID = FUND_PROFILE.DIST_ID
        LEFT JOIN admin_management.TASK_STATUS AS TASK_STATUS
        ON TASK_STATUS.TS_ID = FUND_PROFILE.FUND_STATUS_FUND
        LEFT JOIN distributor_management.USER AS USER
        ON USER.USER_ID = FUND_PROFILE.DIST_USER_ID
        LEFT JOIN admin_management.DISTRIBUTOR_MANAGE_GROUP AS DISTRIBUTOR_MANAGE_GROUP
        ON DISTRIBUTOR_MANAGE_GROUP.DISTRIBUTOR_MANAGE_GROUP_ID = FUND_PROFILE.DIST_USER_GROUP
        LEFT JOIN admin_management.FMS_FUNDTYPE AS FMS_FUNDTYPE
        ON FMS_FUNDTYPE.FMS_FUNDTYPE_ID = FUND_PROFILE.FUND_TYPE
        LEFT JOIN admin_management.FMS_FUNDCATEGORY AS FMS_FUNDCATEGORY
        ON FMS_FUNDCATEGORY.FMS_FUNDCATEGORY_ID = FUND_PROFILE.FUND_CATEGORY
        LEFT JOIN admin_management.FMS_FUND_DOMICILE AS FMS_FUND_DOMICILE
        ON FMS_FUND_DOMICILE.FUND_DOMICILE_ID = FUND_PROFILE.FUND_DOMICILE
        LEFT JOIN admin_management.SETTING_GENERAL AS SETTING_GENERAL
        ON SETTING_GENERAL.SETTING_GENERAL_ID = FUND_PROFILE.FUND_CURR_DENOMINATION
        LEFT JOIN admin_management.FMS_SCHEME_STRUCTURE AS FMS_SCHEME_STRUCTURE
        ON FMS_SCHEME_STRUCTURE.FMS_SCHEME_ID = FUND_PROFILE.FUND_SCHEME
        WHERE 1 = 1
        ".(($this->params["DISTRIBUTORIDS"]!=array(0))?"and FUND_PROFILE.DIST_ID in ( :DISTRIBUTOR_ID)":"")."
         order by FUND_PROFILE.CREATE_TIMESTAMP desc")
        ->params($query_params)
        ->pipe($this->dataStore("FUNDDATAALLREPORT"));

        $this->src("mysql")
        ->query("select DISTRIBUTOR.DISTRIBUTOR_ID AS DISTRIBUTORID,DISTRIBUTOR.DIST_NAME AS DIST_NAME
        from distributor_management.DISTRIBUTOR AS DISTRIBUTOR
        ")
        ->pipe($this->dataStore("DISTRIBUTORLIST"));
        $this->src("mysql")
        ->query("select TASK_STATUS.TS_ID AS TSID,TASK_STATUS.TS_PARAM AS TS_PARAM
        from admin_management.TASK_STATUS AS TASK_STATUS
        WHERE TASK_STATUS.TS_ID IN(22,25,23)
        ")
        ->pipe($this->dataStore("FUNDSTATUSLIST"));
  }
}
